#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SLEEP_TIME 20
#define MAX_UNIT_TIME 5000
#define TIME_SLIDER_MAX 4950 // 5000-4950 = 50
#define TIME_SLIDER_DEFAULT 2000 // 1000ms
#define TIME_SLIDER_MIN 0 // 5000 ms

#define AREA_WIDTH_HEIGHT 10000 // Centimeters ==> [50m x 50m]
#define RENDER_WINDOW_WIDTH_HEIGHT 700 // Pixels
#define OVERVIEW_WIDGET_WINDOW_WIDTH_HEIGHT 700 // Pixels

#define SPATIAL_HASHMAP_CELL_WIDTH 30 // Centimeters
#define SPATIAL_HASHMAP_CELL_HEIGHT 30 // Centimeters

#define MIN_STRENGTH -100
#define MAX_STRENGTH 100

#define RENDER_INTERVAL 200 //ms

#define SIMPLIFIED_SEEDING_V1_SEED_COUNT 1000
#define SIMPLIFIED_SEEDING_V2_SEED_COUNT 1000

/****************************
 * CONFIGURATION PARAMETERS *
 ****************************/
#define SEED_PROPAGATION_RADIUS 50

#define PI 3.14159f

#endif //CONSTANTS_H
